# Form implementation generated from reading ui file '.\mainformpancake3d.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormPancake3D(object):
    def setupUi(self, MainFormPancake3D):
        MainFormPancake3D.setObjectName("MainFormPancake3D")
        MainFormPancake3D.resize(300, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormPancake3D.sizePolicy().hasHeightForWidth())
        MainFormPancake3D.setSizePolicy(sizePolicy)
        MainFormPancake3D.setMinimumSize(QtCore.QSize(300, 100))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormPancake3D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_process = QtWidgets.QPushButton(MainFormPancake3D)
        self.btn_process.setObjectName("btn_process")
        self.verticalLayout.addWidget(self.btn_process)

        self.retranslateUi(MainFormPancake3D)
        QtCore.QMetaObject.connectSlotsByName(MainFormPancake3D)

    def retranslateUi(self, MainFormPancake3D):
        _translate = QtCore.QCoreApplication.translate
        MainFormPancake3D.setWindowTitle(_translate("MainFormPancake3D", "3D Pancake"))
        self.btn_process.setText(_translate("MainFormPancake3D", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormPancake3D = QtWidgets.QWidget()
    ui = Ui_MainFormPancake3D()
    ui.setupUi(MainFormPancake3D)
    MainFormPancake3D.show()
    sys.exit(app.exec())
