# Form implementation generated from reading ui file '.\mainformpancake3d.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormPancake3D(object):
    def setupUi(self, MainFormPancake3D):
        MainFormPancake3D.setObjectName("MainFormPancake3D")
        MainFormPancake3D.resize(350, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormPancake3D.sizePolicy().hasHeightForWidth())
        MainFormPancake3D.setSizePolicy(sizePolicy)
        MainFormPancake3D.setMinimumSize(QtCore.QSize(350, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormPancake3D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_cs = QtWidgets.QLabel(MainFormPancake3D)
        self.label_cs.setObjectName("label_cs")
        self.horizontalLayout_2.addWidget(self.label_cs)
        self.line_edit_c_s = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_c_s.setObjectName("line_edit_c_s")
        self.horizontalLayout_2.addWidget(self.line_edit_c_s)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_xy_scale = QtWidgets.QLabel(MainFormPancake3D)
        self.label_xy_scale.setObjectName("label_xy_scale")
        self.horizontalLayout.addWidget(self.label_xy_scale)
        self.line_edit_xy_scale = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_xy_scale.setObjectName("line_edit_xy_scale")
        self.horizontalLayout.addWidget(self.line_edit_xy_scale)
        self.label_z_scale = QtWidgets.QLabel(MainFormPancake3D)
        self.label_z_scale.setObjectName("label_z_scale")
        self.horizontalLayout.addWidget(self.label_z_scale)
        self.line_edit_z_scale = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_z_scale.setObjectName("line_edit_z_scale")
        self.horizontalLayout.addWidget(self.line_edit_z_scale)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chk_visualize = QtWidgets.QCheckBox(MainFormPancake3D)
        self.chk_visualize.setObjectName("chk_visualize")
        self.verticalLayout.addWidget(self.chk_visualize)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_select_multiroi = QtWidgets.QPushButton(MainFormPancake3D)
        self.btn_select_multiroi.setObjectName("btn_select_multiroi")
        self.horizontalLayout_3.addWidget(self.btn_select_multiroi)
        self.btn_select_roi = QtWidgets.QPushButton(MainFormPancake3D)
        self.btn_select_roi.setObjectName("btn_select_roi")
        self.horizontalLayout_3.addWidget(self.btn_select_roi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_selected = QtWidgets.QLabel(MainFormPancake3D)
        self.label_selected.setObjectName("label_selected")
        self.verticalLayout.addWidget(self.label_selected)
        self.btn_process = QtWidgets.QPushButton(MainFormPancake3D)
        self.btn_process.setObjectName("btn_process")
        self.verticalLayout.addWidget(self.btn_process)
        self.label_output = QtWidgets.QLabel(MainFormPancake3D)
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.verticalLayout.addWidget(self.label_output)

        self.retranslateUi(MainFormPancake3D)
        QtCore.QMetaObject.connectSlotsByName(MainFormPancake3D)

    def retranslateUi(self, MainFormPancake3D):
        _translate = QtCore.QCoreApplication.translate
        MainFormPancake3D.setWindowTitle(_translate("MainFormPancake3D", "3D Pancake"))
        self.label_cs.setText(_translate("MainFormPancake3D", "cs (lower = tighter fit)"))
        self.line_edit_c_s.setText(_translate("MainFormPancake3D", "0.67"))
        self.label_xy_scale.setText(_translate("MainFormPancake3D", "XY Scale (nm):"))
        self.line_edit_xy_scale.setText(_translate("MainFormPancake3D", "5.03"))
        self.label_z_scale.setText(_translate("MainFormPancake3D", "Z Scale (nm):"))
        self.line_edit_z_scale.setText(_translate("MainFormPancake3D", "42.017"))
        self.chk_visualize.setText(_translate("MainFormPancake3D", "Visualize Steps"))
        self.btn_select_multiroi.setText(_translate("MainFormPancake3D", "Select Multiple PSDs (MultiROI)"))
        self.btn_select_roi.setText(_translate("MainFormPancake3D", "Select Single PSD (ROI)"))
        self.label_selected.setText(_translate("MainFormPancake3D", "Selected: None"))
        self.btn_process.setText(_translate("MainFormPancake3D", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormPancake3D = QtWidgets.QWidget()
    ui = Ui_MainFormPancake3D()
    ui.setupUi(MainFormPancake3D)
    MainFormPancake3D.show()
    sys.exit(app.exec())
