# Form implementation generated from reading ui file '.\mainformpancake3d.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainFormPancake3D(object):
    def setupUi(self, MainFormPancake3D):
        MainFormPancake3D.setObjectName("MainFormPancake3D")
        MainFormPancake3D.resize(300, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFormPancake3D.sizePolicy().hasHeightForWidth())
        MainFormPancake3D.setSizePolicy(sizePolicy)
        MainFormPancake3D.setMinimumSize(QtCore.QSize(300, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainFormPancake3D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit_c_s = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_c_s.setObjectName("line_edit_c_s")
        self.horizontalLayout_2.addWidget(self.line_edit_c_s)
        self.label_2 = QtWidgets.QLabel(MainFormPancake3D)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainFormPancake3D)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_edit_xy_scale = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_xy_scale.setObjectName("line_edit_xy_scale")
        self.horizontalLayout.addWidget(self.line_edit_xy_scale)
        self.label_3 = QtWidgets.QLabel(MainFormPancake3D)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.line_edit_z_scale = QtWidgets.QLineEdit(MainFormPancake3D)
        self.line_edit_z_scale.setObjectName("line_edit_z_scale")
        self.horizontalLayout.addWidget(self.line_edit_z_scale)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chk_visualize = QtWidgets.QCheckBox(MainFormPancake3D)
        self.chk_visualize.setObjectName("chk_visualize")
        self.verticalLayout.addWidget(self.chk_visualize)
        self.btn_process = QtWidgets.QPushButton(MainFormPancake3D)
        self.btn_process.setObjectName("btn_process")
        self.verticalLayout.addWidget(self.btn_process)

        self.retranslateUi(MainFormPancake3D)
        QtCore.QMetaObject.connectSlotsByName(MainFormPancake3D)

    def retranslateUi(self, MainFormPancake3D):
        _translate = QtCore.QCoreApplication.translate
        MainFormPancake3D.setWindowTitle(_translate("MainFormPancake3D", "3D Pancake"))
        self.line_edit_c_s.setText(_translate("MainFormPancake3D", "0.67"))
        self.label_2.setText(_translate("MainFormPancake3D", "c_s (higher = more blur)"))
        self.label.setText(_translate("MainFormPancake3D", "XY Scale (nm):"))
        self.line_edit_xy_scale.setText(_translate("MainFormPancake3D", "5.03"))
        self.label_3.setText(_translate("MainFormPancake3D", "Z Scale (nm):"))
        self.line_edit_z_scale.setText(_translate("MainFormPancake3D", "42.017"))
        self.chk_visualize.setText(_translate("MainFormPancake3D", "Visualize Steps"))
        self.btn_process.setText(_translate("MainFormPancake3D", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormPancake3D = QtWidgets.QWidget()
    ui = Ui_MainFormPancake3D()
    ui.setupUi(MainFormPancake3D)
    MainFormPancake3D.show()
    sys.exit(app.exec())
